#ifndef RF_GLOBAL_H
#define RF_GLOBAL_H
#define SG_OPT_SWTCH_ZERO   0x00000001 
#define SG_OPT_SWTCH_ONE    0x00000002 
#define SG_OPT_SWTCH_TWO    0x00000004 
#define SG_OPT_SWTCH_THREE  0x00000008 
#define SG_OPT_SWTCH_FOUR   0x00000010 
#define SG_OPT_SWTCH_FIVE   0x00000020 
#define SG_OPT_SWTCH_SIX    0x00000040 
#define SG_OPT_SWTCH_SEVEN  0x00000080 
#define SG_OPT_REAL_TIME    0x00000100 
#define SG_CPU_TIME   0  
#define SG_MEMB_ID        1  
#define SG_BOOT_CT        2  
#define SG_LEAF_CT        3  
#define SG_SEED_ID        4  
#define SG_TREE_ID        5  
#define SG_NODE_ID        6  
#define SG_NODE_SZ        7  
#define SG_BR_NODE_ID     8  
#define SG_PR_NODE_ID     9  
#define SG_BSF_ORD       10  
#define SG_PARM_ID       11  
#define SG_CONT_PT       12  
#define SG_MWCP_SZ       13  
#define SG_MWCP_PT       14  
#define SG_MWCP_CT       15  
#define SG_FS_REC_ID     16  
#define SG_NODE_STAT     17  
#define SG_RMBR_TN_CT    18  
#define SG_IMBR_TN_CT    19  
#define SG_OMBR_TN_CT    20  
#define SG_RMBR_TN_ID    21  
#define SG_IMBR_TN_ID    22  
#define SG_OMBR_TN_ID    23  
#define SG_NLSN_TN       24  
#define SG_HAZR_TN       25  
#define SG_NLSN_IBG      26  
#define SG_HAZR_IBG      27  
#define SG_HAZR_RAW_IBG  28  
#define SG_NLSN_OOB      29  
#define SG_HAZR_OOB      30  
#define SG_HAZR_RAW_OOB  31  
#define SG_T_HAZ_TM_IDX  32  
#define SG_T_HAZ_TM_CNT  33  
#define SG_RISK_IBG      34  
#define SG_RISK_OOB      35  
#define SG_RISK_RAW_IBG  36  
#define SG_RISK_RAW_OOB  37  
#define SG_ENSB_ID       38  
#define SG_NODE_RISK     39  
#define SG_NODE_RISK_RAW 40  
#define SG_TREE_RISK_IBG     41  
#define SG_TREE_RISK_OOB     42  
#define SG_TREE_RISK_RAW_IBG 43  
#define SG_TREE_RISK_RAW_OOB 44  
#define SG_OPT_LO_GROW       45  
#define SG_OPT_HI_GROW       46  
#define SG_SEXP_SIZE         47  
#define REGR_CDL     1
#define CLAS_CDL     2
#define REGR_CRT     3
#define CLAS_CRT     4
#define RAND_CRT     5
#define SG_SURV_TDC  6
#define SG_SURV_NLS  7
#define SG_SPLIT_ON_TDC 1
#define SG_SPLIT_NO_TDC 2
#define ROOT 0x00
#define OUTC_CART   0x01
#define OUTC_LASSO  0x02
#endif
