#ifndef RF_STACK_SUBJECT_INFO_H
#define RF_STACK_SUBJECT_INFO_H
char stackSubjectArraysOnly(char     mode,
                            uint     timeIndex,
                            uint     statusIndex,
                            uint     startTimeIndex,
                            uint     observationSize,
                            uint    *subjIn,
                            uint    *subjSize,
                            uint   **subjSlot,
                            uint   **subjSlotCount,
                            uint  ***subjList,
                            uint   **caseMap,
                            uint   **subjMap,
                            uint    *subjCount);
void unstackSubjectArraysOnly(char     mode,
                              uint     timeIndex,
                              uint     statusIndex,
                              uint     startTimeIndex,
                              uint     observationSize,
                              uint     subjCount,
                              uint    *subjSlot,
                              uint    *subjSlotCount,
                              uint   **subjList,
                              uint    *caseMap,
                              uint    *subjMap);
void stackSubjectTimeInterestIndex(char mode,
                                   uint timeIndex,
                                   uint statusIndex,
                                   uint startTimeIndex,
                                   uint observationSize,
                                   double **responseIn,
                                   uint  subjCount,
                                   uint *subjIn,
                                   uint *subjMap,
                                   uint *subjSlot,
                                   uint    sortedTimeInterestSize,
                                   double *timeInterest,
                                   uint  **timeInterestIntervalCount,
                                   uint ***timeInterestIntervalIndex,
                                   uint  **timeInterestSubjTailIndex,
                                   uint  **subjTailCaseMap);
void unstackSubjectTimeInterestIndex(char mode,
                                     uint observationSize,
                                     uint  subjCount,
                                     uint  *timeInterestIntervalCount,
                                     uint **timeInterestIntervalIndex,
                                     uint  *timeInterestSubjTailIndex,
                                     uint  *subjTailCaseMap);
#endif
